#!/bin/bash

# shell script to create a basic VM using the Nutanix v4 Prism REST API
# requires the existence of a JSON-formatted file that contains:
#
# cluster/CVM IP
# username
# the name of the VM to be created
#
# this file must be named "create_vm.json" and be formatted as follows:
#
# {"cluster_ip":"10.0.0.1","username":"admin","vm_name":"BasicVMViaAPIv3","cluster_extid":"<cluster_extid_here>"}

JSON_FILE="./create_vm.json"
JSON_CONTENTS="`cat ${JSON_FILE}`"

JQ=`command -v jq`
CURL=`command -v curl`
UUIDGEN=`command -v uuidgen`

if [ "$JQ" = "" ] || [ "$CURL" = "" ] || [ "$UUIDGEN" = "" ]; then
	echo "Required command missing (jq, curl or uuidgen)."
else
	PC_IP=`echo -n $JSON_CONTENTS | jq -r ".pc_ip"`
	USERNAME=`echo -n $JSON_CONTENTS | jq -r ".username"`
	VM_NAME=`echo -n $JSON_CONTENTS | jq -r ".vm_name"`
    CLUSTER_EXTID=`echo -n $JSON_CONTENTS | jq -r ".cluster_extid"`

    # generate a UUID to be used as the value of the Ntnx-Request-Id header
    REQUEST_ID=`uuidgen`

	# get the password from the user
	echo "Enter your Prism Central password (will not be shown on screen):"
	read -s PASSWORD

	# generate the HTTP Basic Authorization header
	AUTH_HEADER="`echo -n $USERNAME:$PASSWORD | base64`"

	# submit the request
	curl --insecure -X POST \
        --connect-timeout 5 \
	https://$PC_IP:9440/api/vmm/v4.2/ahv/config/vms \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -H "Authorization: Basic $AUTH_HEADER" \
  -H "Ntnx-Request-Id: $REQUEST_ID" \
  -H "cache-control: no-cache" \
  -d "{
        \"name\": \"$VM_NAME\",
        \"description\": \"VM created from shell code sample and Nutanix v4 APIs\",
        \"cluster\": {
            \"extId\": \"$CLUSTER_EXTID\"
        }
      }"

fi