#cloud-config
users:
  - name: nutanix
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQD486FNEscDkK4xqyvT5Syg+z2pjvJVp7ndBGcq3jhS8SFcelgsam2H3wHnV/ybH3dxc8a+Qd1RdACCqT5F+798BJj8XOjOAktI35yQd8Hh8jmUAHzmwh8QUGgFKnmsyI7aX3DLFmHrfp31LlHFuiNNCw9vW1V9klfTXDxuqwC243qgGNYqgeCbHMBHW21Ou+YhuZKAaacNuhgtaE5uw8kmCbg2KJTgxVSzcac3WU1Jih59fS5xIox6nEAGwQeo3jsBg2QT5oZLgBA4uo+ZHoxysbVaabd2XpEi+Pzf2NYJl6cYomAq2uNmieWBe0FPsBPPL8rmbG+qyg/EDfBWJuXjE5/eqDTbeb9/csRaXF94nhRgpMpBlcP7kVmeHmq4OeImbZbu9hWjO81VLss7L9MSaPK4Cl1ULXGO0NswtVqXlSz4tdSjpuYt4hSW1o2Hh58QMqoBmKAa+tw5PvpaMuVyRbklRFBmoBN9t6hb3tUDQwYLlO6FU73Ixhp8sPQelpcwtlh/SSAvncyEVOku65pJ8a0WfrmLCSIx4/KKbXH09eOY2T/U6BeFDXsorXFwN2/vaGJXB0HCMYI+RhG/vaj5BsJ4GL8iHBiXG7A7MEQel4j6UWzThFFZpBz+B2gs+aJrtf3pqYABWmLepn1rd049gCixyMnuPDo6+H7FD+GD6w== no-reply@acme.com
    lock_passwd: false
    passwd: $6$4guEcDvX$HBHMFKXp4x/Eutj0OW5JGC6f1toudbYs.q.WkvXGbUxUTzNcHawKRRwrPehIxSXHVc70jFOp3yb8yZgjGUuET.

# note: the encoded password hash above is "nutanix/4u" (without the quotes)

package_update: true
package_upgrade: true

hostname: rocky-linux-tools-vm

packages:
  - jq
  - vim

runcmd:
  - dnf -y install epel-release
  - dnf -y config-manager --set-enabled crb || true
  - dnf -y install nginx
  - systemctl stop firewalld
  - systemctl disable firewalld
  - /sbin/setenforce 0
  - sed -i -e 's/enforcing/disabled/g' /etc/selinux/config
  - systemctl enable nginx --now

final_message: Rocky Linux Tools Machine setup successfully!
